#!/bin/bash

echo "=== WDROŻENIE Z NOWYMI KLUCZAMI SUPABASE ==="
echo ""
echo "Ta instrukcja używa NOWYCH kluczy Supabase (sb_publishable_, sb_secret_)"
echo ""
echo "WYKONAJ TE KOMENDY NA SERWERZE (przez Web Console):"
echo ""
echo "=========================================="
echo ""
echo "# 1. Przejdź do katalogu aplikacji"
echo "cd /opt/Secure-Messenger"
echo ""
echo "# 2. Pobierz najnowsze zmiany z GitHub"
echo "git pull origin main"
echo ""
echo "# 3. Utwórz plik .env.production z nowymi kluczami"
echo "cat > .env.production << 'EOF'"
echo "# Production environment variables"
echo "NODE_ENV=production"
echo ""
echo "# Supabase Configuration (NEW KEY FORMAT)"
echo "VITE_SUPABASE_URL=https://fyxmppbrealxwnstuzuk.supabase.co"
echo "VITE_SUPABASE_KEY=sb_publishable_Jau8JdiOFfVKQOM1svLxMQ_9-sBqnKc"
echo "SUPABASE_SERVICE_KEY=sb_secret_ek5NhQ2-BVZd-7yHw3RYhw_-sx2qOse"
echo ""
echo "# Application Settings"
echo "PORT=3000"
echo "HOST=0.0.0.0"
echo ""
echo "# Security"
echo "CORS_ORIGIN=http://5.22.223.49,http://secure-messenger.info,https://secure-messenger.info"
echo ""
echo "# Logging"
echo "LOG_LEVEL=info"
echo "EOF"
echo ""
echo "# 4. Zatrzym aplikację"
echo "docker-compose -f deployment/docker/docker-compose.production.yml down"
echo ""
echo "# 5. Przebuduj aplikację (bez cache aby użyć nowego kodu)"
echo "docker-compose -f deployment/docker/docker-compose.production.yml build --no-cache"
echo ""
echo "# 6. Uruchom aplikację"
echo "docker-compose -f deployment/docker/docker-compose.production.yml up -d"
echo ""
echo "# 7. Sprawdź status"
echo "docker ps"
echo ""
echo "# 8. Sprawdź logi"
echo "docker logs secure-messenger-app --tail 50"
echo ""
echo "# 9. Test aplikacji"
echo "curl http://localhost/"
echo "curl http://localhost/health"
echo ""
echo "=========================================="
echo ""
echo "APLIKACJA POWINNA BYĆ DOSTĘPNA POD:"
echo "- http://5.22.223.49"
echo "- http://secure-messenger.info (gdy DNS się rozpropaguje)"
echo ""
echo "Jeśli pojawią się błędy, sprawdź logi:"
echo "docker logs secure-messenger-app -f"
