#!/bin/bash

# Instrukcje aktualizacji serwera z nowymi kluczami API
# Wykonaj te komendy przez Web Console w UpCloud

echo "=== AKTUALIZACJA KLUCZY API NA SERWERZE ==="
echo ""
echo "1. Połącz się z serwerem przez Web Console"
echo "2. Wykonaj poniższe komendy:"
echo ""
echo "# Przejdź do katalogu aplikacji"
echo "cd /opt/Secure-Messenger"
echo ""
echo "# Utwórz/zaktualizuj plik .env.production"
echo "cat > .env.production << 'EOF'"
echo "# Production environment variables"
echo "NODE_ENV=production"
echo ""
echo "# Supabase Configuration"
echo "VITE_SUPABASE_URL=https://fyxmppbrealxwnstuzuk.supabase.co"
echo "VITE_SUPABASE_ANON_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5eG1wcGJyZWFseHduc3R1enVrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTk2MDcyNjYsImV4cCI6MjA3NTE4MzI2Nn0.P_u5yDgASYwx-ImH-QhTTqAO8xM96DvUkgJ1tCm-8Pw"
echo "SUPABASE_SERVICE_ROLE_KEY=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5eG1wcGJyZWFseHduc3R1enVrIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc1OTYwNzI2NiwiZXhwIjoyMDc1MTgzMjY2fQ._exYkOlAqEYUMTyqt8AByk2IE7rqIUghG3rtbpsedBI"
echo ""
echo "# Application Settings"
echo "PORT=3000"
echo "HOST=0.0.0.0"
echo ""
echo "# Security"
echo "CORS_ORIGIN=http://5.22.223.49,http://secure-messenger.info,https://secure-messenger.info"
echo ""
echo "# Logging"
echo "LOG_LEVEL=info"
echo "EOF"
echo ""
echo "# Pobierz najnowsze zmiany z GitHub"
echo "git pull origin main"
echo ""
echo "# Zatrzymaj aplikację"
echo "docker-compose -f deployment/docker/docker-compose.production.yml down"
echo ""
echo "# Przebuduj aplikację z nowymi zmiennymi"
echo "docker-compose -f deployment/docker/docker-compose.production.yml build --no-cache"
echo ""
echo "# Uruchom aplikację"
echo "docker-compose -f deployment/docker/docker-compose.production.yml up -d"
echo ""
echo "# Sprawdź status"
echo "docker ps"
echo ""
echo "# Sprawdź logi (opcjonalnie)"
echo "docker logs secure-messenger-app --tail 50"
echo ""
echo "=== KONIEC ==="
