#!/bin/bash

echo "🚀 AKTUALIZACJA APLIKACJI NA SERWERZE"
echo "====================================="
echo ""
echo "✅ Przygotowania zakończone:"
echo "  - Certbot zainstalowany"
echo "  - Confirm email wyłączony w Supabase"
echo ""
echo "Teraz wykonaj poniższe komendy NA SERWERZE:"
echo ""
echo "═══════════════════════════════════════════"
echo ""
echo "# KROK 1: Przejdź do katalogu aplikacji"
echo "cd /opt/Secure-Messenger"
echo ""
echo "# KROK 2: Pobierz najnowsze zmiany z GitHub"
echo "git pull origin main"
echo ""
echo "# KROK 3: Utwórz plik konfiguracyjny"
echo "cat > .env.production << 'EOF'"
echo "NODE_ENV=production"
echo "VITE_SUPABASE_URL=https://fyxmppbrealxwnstuzuk.supabase.co"
echo "VITE_SUPABASE_KEY=sb_publishable_Jau8JdiOFfVKQOM1svLxMQ_9-sBqnKc"
echo "SUPABASE_SERVICE_KEY=sb_secret_ek5NhQ2-BVZd-7yHw3RYhw_-sx2qOse"
echo "PORT=3000"
echo "HOST=0.0.0.0"
echo "CORS_ORIGIN=https://secure-messenger.info,http://5.22.223.49"
echo "LOG_LEVEL=info"
echo "EOF"
echo ""
echo "# KROK 4: Wygeneruj certyfikat SSL (ZMIEŃ EMAIL!)"
echo "sudo certbot certonly --standalone --non-interactive --agree-tos --email TWOJ-EMAIL@example.com -d secure-messenger.info -d www.secure-messenger.info"
echo ""
echo "# KROK 5: Skonfiguruj SSL w Nginx"
echo "sudo bash deployment/scripts/setup-ssl.sh"
echo ""
echo "# KROK 6: Restart aplikacji"
echo "docker-compose -f deployment/docker/docker-compose.production.yml down"
echo "docker-compose -f deployment/docker/docker-compose.production.yml build --no-cache"
echo "docker-compose -f deployment/docker/docker-compose.production.yml up -d"
echo ""
echo "# KROK 7: Sprawdź status"
echo "docker ps"
echo "docker logs secure-messenger-app --tail 50"
echo ""
echo "# KROK 8: Test HTTPS"
echo "curl -I https://secure-messenger.info"
echo ""
echo "═══════════════════════════════════════════"
echo ""
echo "APLIKACJA BĘDZIE DOSTĘPNA POD:"
echo "🔒 https://secure-messenger.info"
echo "🔒 https://www.secure-messenger.info"
echo ""
echo "⚠️ PAMIĘTAJ: Zamień TWOJ-EMAIL@example.com na swój email!"
