#!/bin/bash

echo "=== AKTUALIZACJA SERWERA Z KLUCZAMI JWT ==="
echo ""
echo "WAŻNE: Musisz najpierw znaleźć klucze JWT w Supabase Dashboard!"
echo ""
echo "Masz Legacy JWT secret, ale potrzebujesz:"
echo "1. anon key (public) - zaczyna się od eyJ..."
echo "2. service_role key - zaczyna się od eyJ..."
echo ""
echo "Te klucze powinny być widoczne w Supabase Dashboard"
echo "obok Legacy JWT secret który znalazłeś."
echo ""
echo "=========================================="
echo ""
echo "GDY ZNAJDZIESZ KLUCZE JWT, wykonaj na serwerze:"
echo ""
echo "# 1. Połącz się przez Web Console"
echo ""
echo "# 2. Przejdź do katalogu aplikacji"
echo "cd /opt/Secure-Messenger"
echo ""
echo "# 3. Pobierz najnowsze zmiany"
echo "git pull origin main"
echo ""
echo "# 4. Edytuj plik .env.production"
echo "nano .env.production"
echo ""
echo "# 5. Zaktualizuj klucze (zastąp TUTAJ_WKLEJ_KLUCZ odpowiednimi kluczami):"
echo ""
echo "NODE_ENV=production"
echo "VITE_SUPABASE_URL=https://fyxmppbrealxwnstuzuk.supabase.co"
echo "VITE_SUPABASE_ANON_KEY=TUTAJ_WKLEJ_ANON_KEY"
echo "SUPABASE_SERVICE_ROLE_KEY=TUTAJ_WKLEJ_SERVICE_ROLE_KEY"
echo "PORT=3000"
echo "HOST=0.0.0.0"
echo "CORS_ORIGIN=http://5.22.223.49,http://secure-messenger.info,https://secure-messenger.info"
echo "LOG_LEVEL=info"
echo ""
echo "# 6. Zapisz plik (Ctrl+O, Enter, Ctrl+X)"
echo ""
echo "# 7. Restart aplikacji"
echo "docker-compose -f deployment/docker/docker-compose.production.yml down"
echo "docker-compose -f deployment/docker/docker-compose.production.yml build --no-cache"
echo "docker-compose -f deployment/docker/docker-compose.production.yml up -d"
echo ""
echo "# 8. Sprawdź status"
echo "docker ps"
echo "docker logs secure-messenger-app --tail 50"
echo ""
echo "# 9. Test aplikacji"
echo "curl http://localhost/health"
echo ""
echo "=========================================="
echo ""
echo "GDZIE SZUKAĆ KLUCZY JWT:"
echo "1. Supabase Dashboard > Settings > API"
echo "2. Obok 'Legacy JWT secret' powinny być:"
echo "   - anon (public) key"
echo "   - service_role key"
echo "3. Kliknij 'Reveal' jeśli są ukryte"
