version: '3.8'

services:
  secure-messenger:
    image: secure-messenger:latest
    build:
      context: ../../
      dockerfile: deployment/docker/Dockerfile.production
    container_name: secure-messenger-app
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - NODE_ENV=production
    env_file:
      - ../../.env.production
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - logs:/var/log/nginx
    networks:
      - secure-messenger-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "com.secure-messenger.version=1.0.0"
      - "com.secure-messenger.environment=production"
      - "com.secure-messenger.maintainer=FSliwa"

  nginx-proxy:
    image: nginx:alpine
    container_name: secure-messenger-nginx
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - logs:/var/log/nginx
    networks:
      - secure-messenger-network
    depends_on:
      - secure-messenger

volumes:
  logs:
    driver: local

networks:
  secure-messenger-network:
    driver: bridge
